version: "3.8"
services:
  postgres:
    image: postgres:16-alpine
    container_name: dbusiness-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbusiness
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: dbusiness-app
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/dbusiness?schema=public
  #     - NEXTAUTH_SECRET=your-secret-key-here
  #     - NEXTAUTH_URL=http://localhost:3000
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

volumes:
  postgres_data:
